solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [ArmCartesian]

    
constraints: [JointLimits, VelocityLimits]

ArmCartesian:
    name: "ArmCartesian"
    type: Cartesian
    distal_link: tcp_1
    base_link: base_link
    lambda: 0.1
    active: true

ArmCartesianLinear:
    type: "Subtask"
    task: "ArmCartesian"
    #type: "Cartesian"
    distal_link: tcp_1
    base_link: base_link
    lambda: 0.1
    active: true
    indices: [0, 1, 2]
    
ArmCartesianAngular:
    type: "Subtask"
    task: "ArmCartesian"
    #type: "Cartesian"
    distal_link: tcp_1
    base_link: base_link
    lambda: 0.1
    active: true
    indices: [3, 4, 5]

Postural:
    type: Postural
    lambda: 0.01
    weight: 0.001

JointLimits:
    type: JointLimits

VelocityLimits:
    type: VelocityLimits
