solver_options:
    regularization: 1e-4
    back_end: qpoases

stack:
    - [arm_ee]

    
constraints: [JointLimits, VelocityLimits]

arm_ee:
    type: Cartesian
    distal_link: tcp_1
    base_link: base_link
    lambda: 0.1

Postural:
    type: Postural
    lambda: 0.01
    weight: 0.001
    
JointLimits:
    type: JointLimits


VelocityLimits:
    type: VelocityLimits