#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from rclpy.clock import Clock
from geometry_msgs.msg import PoseStamped, TwistStamped
from sensor_msgs.msg import JointState
class GripperPoseCommandPublisher(Node):

    def __init__(self):
        super().__init__('gripper_pose_command_publisher')
        # self.publisher_ = self.create_publisher(PoseStamped, '/cartesian/ArmCartesian/reference', 10)
        self.publisher_ = self.create_publisher(JointState, '/cartesian/ArmPostural/reference', 10)
        timer_period = 1 / 100  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.get_logger().info('GripperPoseCommandPublisher node has been started.')
        self.homing_ee_down = {
            'joint_names': ['j_arm1_1', 'j_arm1_2', 'j_arm1_3', 'j_arm1_4', 'j_arm1_5', 'j_arm1_6'],
            'joint_positions': [0.0, 0.29, -1.85, 0.0, 0.97, 0.0, 0.0],
            'joint_positions2': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            'joint_positions3': [0.8485896587371826, -0.03604533523321152, -2.200000047683716, -2.700000047683716, 2.200000047683716, 2.347837018966675],

        }

    def timer_callback(self):
        # msg = PoseStamped()
        # msg.header.stamp = Clock().now().to_msg()  # correct ROS time
        # msg.header.frame_id = 'base_link'
        # msg.pose.position.x = 0.2
        # msg.pose.position.y = 0.1
        # msg.pose.position.z = 0.7
        # msg.pose.orientation.x = 0.0
        # msg.pose.orientation.y = 0.0
        # msg.pose.orientation.z = 0.707
        # msg.pose.orientation.w = 0.707
        # msg.pose.position.x = 0.0
        # msg.pose.position.y = 0.5
        # msg.pose.position.z = 0.4
        # msg.pose.orientation.x = 0.0
        # msg.pose.orientation.y = 0.0
        # msg.pose.orientation.z = 0.0
        # msg.pose.orientation.w = 1.0


        msg = JointState()
        msg.header.stamp = Clock().now().to_msg()
        msg.header.frame_id = 'base_link'
        msg.name = self.homing_ee_down['joint_names']
        msg.position = self.homing_ee_down['joint_positions']
        msg.velocity = []
        msg.effort = []
            

        self.publisher_.publish(msg)
        self.get_logger().info(f'Published GripperPoseCommand: {msg}')



def main(args=None):
    rclpy.init(args=args)
    node = GripperPoseCommandPublisher()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()