#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.clock import Clock
from sensor_msgs.msg import JointState

class GripperCommandPublisher(Node):
    def __init__(self):
        super().__init__('gripper_command_publisher')
        self.publisher_ = self.create_publisher(JointState, '/xbotcore/gripper/dagana_1/command', 10)
        self.timer = self.create_timer(0.01, self.publish_gripper_command)  # Publish every second
        self.get_logger().info('GripperCommandPublisher node has been started.')

    def publish_gripper_command(self):
        msg = JointState()
        msg.header.stamp = Clock().now().to_msg()  # correct ROS time
        msg.header.frame_id = ''
        msg.name = ['dagana_1_claw_joint']
        msg.position = [0.0]  # Example positions
        msg.velocity = []  # Example velocities
        msg.effort = []

        self.publisher_.publish(msg)
        self.get_logger().info(f'Published GripperCommand: {msg}')

def main(args=None):
    rclpy.init(args=args)
    node = GripperCommandPublisher()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()