#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.clock import Clock
from xbot_msgs.msg import JointCommand

class JointCommandPublisher(Node):
    def __init__(self):
        super().__init__('joint_command_publisher')
        self.publisher_ = self.create_publisher(JointCommand, '/xbotcore/command', 10)
        self.timer = self.create_timer(0.01, self.publish_joint_command)  # Publish every second
        self.get_logger().info('JointCommandPublisher node has been started.')

    def publish_joint_command(self):
        msg = JointCommand()
        msg.header.stamp = Clock().now().to_msg()  # correct ROS time
        msg.header.frame_id = ''
        msg.name = ['j_arm1_1', 'j_arm1_2', 'j_arm1_3', 'j_arm1_4', 'j_arm1_5', 'j_arm1_6', 'dagana_1_claw_joint']  # Example joint names
        msg.position = [0.0, 0.29, -1.85, 0.0, 0.97, 1.51, 1.0]  # Example positions
        msg.velocity = []  # Example velocities
        # msg.effort = [0.0, 205.0, 0.0, 0.0, 0.0, 0.0]    # Example efforts
        msg.effort = []
        msg.stiffness = [4000, 4000, 4000, 4000, 600, 600, 10]  # Example stiffnesses
        msg.damping = [40, 40, 40, 40, 6, 6, 0.5]  # Example dampings
        msg.ctrl_mode = [1, 1, 1, 1, 1, 1, 1]
        self.publisher_.publish(msg)
        self.get_logger().info(f'Published JointCommand: {msg}')

def main(args=None):
    rclpy.init(args=args)
    node = JointCommandPublisher()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()