controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j_arm1_1
      - j_arm1_2
      - j_arm1_3
      - j_arm1_4
      - j_arm1_5
      - j_arm1_6
  - name: fake_dagana_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: arm
    pose: home