arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j_arm1_1
    - j_arm1_2
    - j_arm1_3
    - j_arm1_4
    - j_arm1_5
    - j_arm1_6
  gains:
    j_arm1_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm1_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm1_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm1_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm1_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_arm1_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1