controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j_arm1_1
      - j_arm1_2
      - j_arm1_3
      - j_arm1_4
      - j_arm1_5
      - j_arm1_6