controller_list:
 - name: ""
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - j_arm1_1
    - j_arm1_2
    - j_arm1_3
    - j_arm1_4
    - j_arm1_5
    - j_arm1_6
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: chains
    pose: home
